```yml
name: waylo
description: WAYLO 국내 여행 AI 일정 추천 앱
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 카카오맵 연동
  flutter_kakao_map: ^1.0.0

  # Material Design 3
  flutter/material.dart:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 빌드 관련
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

```